"""题目提供的26条校园活动模拟数据"""

ACTIVITIES_DATA = [
    {
        "id": 1,
        "title": '\u201c蓝桥杯\u201d程序设计校内训练营',
        "content": "9月24日22:00报名截止；原计划9月20日起每周六19:00训练；面向全校学生；零基础可参加",
        "category": "competition",
        "source": "official",
        "deadline": "2026-09-24T22:00",
        "location": None,
        "target_audience": "全校学生",
        "status": "upcoming",
    },
    {
        "id": 2,
        "title": "AI应用入门公开课",
        "content": "9月19日19:00；计算机学院教学楼；面向全校学生；无需报名；预计90分钟",
        "category": "lecture",
        "source": "college",
        "deadline": None,
        "location": "计算机学院教学楼",
        "target_audience": "全校学生",
        "status": "upcoming",
    },
    {
        "id": 3,
        "title": "大学生创新创业项目团队招募",
        "content": "招募开发、设计、材料成员；每周需稳定投入4小时以上；9月22日18:00截止；需提交简短自我介绍",
        "category": "recruit",
        "source": "student",
        "deadline": "2026-09-22T18:00",
        "location": None,
        "target_audience": None,
        "status": "upcoming",
    },
    {
        "id": 4,
        "title": "数学建模竞赛经验分享会",
        "content": "直播时间为9月18日19:30；不限专业；直播已结束，活动方预计9月20日上传回放",
        "category": "lecture",
        "source": "official",
        "deadline": None,
        "location": "线上直播",
        "target_audience": "不限专业",
        "status": "ended",
    },
    {
        "id": 5,
        "title": "校园公益志愿服务活动",
        "content": "活动时间9月27日8:30—17:00；9月20日12:00报名截止；预计服务8小时；需提前到场签到",
        "category": "volunteer",
        "source": "official",
        "deadline": "2026-09-20T12:00",
        "location": None,
        "target_audience": None,
        "status": "upcoming",
    },
    {
        "id": 6,
        "title": "Web开发零基础学习小组",
        "content": "9月23日起每周三19:30开展，共6周；面向零基础学生；限30人；报名时间未注明，满员即止",
        "category": "study_group",
        "source": "student",
        "deadline": None,
        "location": None,
        "target_audience": "零基础学生",
        "status": "upcoming",
    },
    {
        "id": 7,
        "title": "AI创新应用挑战赛",
        "content": "2—4人组队；9月21日18:00前完成校内意向登记；10月20日提交作品；意向登记不等同于最终作品提交",
        "category": "competition",
        "source": "official",
        "deadline": "2026-09-21T18:00",
        "location": None,
        "target_audience": None,
        "status": "upcoming",
    },
    {
        "id": 8,
        "title": "校园软件项目组招募",
        "content": "开发校园实用工具；面向大一、大二学生；希望成员了解Git基本操作；每周预计投入5小时；长期招募，满员即止",
        "category": "recruit",
        "source": "student",
        "deadline": None,
        "location": None,
        "target_audience": "大一、大二学生",
        "status": "upcoming",
    },
    {
        "id": 9,
        "title": "程序设计训练营补充通知",
        "content": "因场地调整，首次训练改为9月21日19:30，地点改至实验楼A402；已报名同学无需重复提交；报名截止时间不变",
        "category": "notice",
        "source": "official",
        "deadline": None,
        "location": "实验楼A402",
        "target_audience": None,
        "status": "upcoming",
        "is_supplement": True,
        "original_id": 1,
    },
    {
        "id": 10,
        "title": "前端开发经验交流会",
        "content": "9月19日15:00—16:30；线下A201并同步线上直播；无需报名",
        "category": "lecture",
        "source": "student",
        "deadline": None,
        "location": "A201 / 线上直播",
        "target_audience": None,
        "status": "upcoming",
    },
    {
        "id": 11,
        "title": "大学生科研入门分享会",
        "content": "9月21日19:00—20:30；介绍论文检索、学生科研项目和导师联系方法；面向全校学生",
        "category": "lecture",
        "source": "official",
        "deadline": None,
        "location": None,
        "target_audience": "全校学生",
        "status": "upcoming",
    },
    {
        "id": 12,
        "title": "全国高校计算机能力挑战赛",
        "content": "面向本科生；10月5日23:59报名截止；个人参赛；具体费用信息未提供",
        "category": "competition",
        "source": "official",
        "deadline": "2026-10-05T23:59",
        "location": None,
        "target_audience": "本科生",
        "status": "upcoming",
    },
    {
        "id": 13,
        "title": "科研助理招募",
        "content": "协助数据整理和实验工作；仅限大二及以上学生；每周预计投入6小时；9月21日截止报名",
        "category": "recruit",
        "source": "official",
        "deadline": "2026-09-21T23:59",
        "location": None,
        "target_audience": "大二及以上学生",
        "status": "upcoming",
    },
    {
        "id": 14,
        "title": "Git与GitHub零基础工作坊",
        "content": "9月21日19:00—20:30；主要面向大一新生；限40人；需提前预约，提交报名表不代表最终录取，以审核通知为准",
        "category": "workshop",
        "source": "official",
        "deadline": None,
        "location": None,
        "target_audience": "大一新生",
        "status": "upcoming",
    },
    {
        "id": 15,
        "title": "AI应用创意挑战",
        "content": "9月23日23:59前提交创意方案；9月30日前提交最终作品；允许个人或团队参加；进入展示环节后可再组队",
        "category": "competition",
        "source": "official",
        "deadline": "2026-09-23T23:59",
        "location": None,
        "target_audience": None,
        "status": "upcoming",
    },
    {
        "id": 16,
        "title": "校园摄影志愿者招募",
        "content": "长期招募；参与校内大型活动摄影；具体报名截止时间未注明；有摄影设备者优先但不作硬性要求",
        "category": "volunteer",
        "source": "official",
        "deadline": None,
        "location": None,
        "target_audience": None,
        "status": "upcoming",
    },
    {
        "id": 17,
        "title": "Python程序设计学习资料合集",
        "content": "包含课程、练习和项目案例；资料长期开放；当前网盘提取信息有效至9月22日，后续将统一更新",
        "category": "resource",
        "source": "official",
        "deadline": "2026-09-22T23:59",
        "location": "线上",
        "target_audience": None,
        "status": "upcoming",
    },
    {
        "id": 18,
        "title": "网络安全兴趣交流小组",
        "content": "首次交流时间为9月19日19:30；之后每两周开展一次；面向CTF、Web安全等方向感兴趣的学生；不限基础",
        "category": "study_group",
        "source": "student",
        "deadline": None,
        "location": None,
        "target_audience": "对CTF、Web安全感兴趣的学生",
        "status": "upcoming",
    },
    {
        "id": 19,
        "title": "学生创新项目路演观摩",
        "content": "活动时间9月20日14:30；原报名截止时间为9月18日22:00；活动方说明如现场仍有余位，可接受候补入场",
        "category": "lecture",
        "source": "official",
        "deadline": "2026-09-18T22:00",
        "location": None,
        "target_audience": None,
        "status": "upcoming",
    },
    {
        "id": 20,
        "title": "创新创业项目团队补充说明",
        "content": "开发方向名额已满，现主要补充设计与材料成员；9月22日18:00截止；此前已投递者无需重复提交",
        "category": "notice",
        "source": "student",
        "deadline": "2026-09-22T18:00",
        "location": None,
        "target_audience": None,
        "status": "upcoming",
        "is_supplement": True,
        "original_id": 3,
    },
    {
        "id": 21,
        "title": "计算机学院AI产品设计分享会",
        "content": "计算机学院发布；9月20日19:00；明德楼B203；面向全校学生；无需报名，座位有限",
        "category": "lecture",
        "source": "college",
        "deadline": None,
        "location": "明德楼B203",
        "target_audience": "全校学生",
        "status": "upcoming",
    },
    {
        "id": 22,
        "title": "学生发起｜周末羽毛球约球",
        "content": "学生个人发布；9月20日16:00；计划6—8人；费用AA；场地待最终确认",
        "category": "sport",
        "source": "student",
        "deadline": None,
        "location": "待定",
        "target_audience": None,
        "status": "upcoming",
    },
    {
        "id": 23,
        "title": "学生发起｜AI工具交流搭子招募",
        "content": "学生个人发布；拟于9月21日晚开展；欢迎零基础；报名后拉群；具体地点未确定",
        "category": "team",
        "source": "student",
        "deadline": None,
        "location": "待定",
        "target_audience": "欢迎零基础",
        "status": "upcoming",
    },
    {
        "id": 24,
        "title": '学生发起\uff5c\u201c校园兼职福利分享\u201d',
        "content": '学生个人发布；称\u201c零门槛、日结\u201d，要求添加私人微信获取详情；未提供主办方、地点和完整内容',
        "category": "other",
        "source": "student",
        "deadline": None,
        "location": None,
        "target_audience": None,
        "status": "upcoming",
        "risk_flag": True,
        "risk_reason": "信息不完整，要求添加私人微信，缺少主办方和地点信息，可能存在推广或安全风险",
    },
    {
        "id": 25,
        "title": "学生发起｜数码新品体验交流",
        "content": "学生个人发布；标题为技术交流，正文主要介绍某商家优惠及购买链接；活动时间、地点未注明",
        "category": "other",
        "source": "student",
        "deadline": None,
        "location": None,
        "target_audience": None,
        "status": "upcoming",
        "risk_flag": True,
        "risk_reason": "标题与实际内容不符，正文主要为商家推广信息和购买链接，疑似广告",
    },
    {
        "id": 26,
        "title": "外国语学院校园语言角",
        "content": "外国语学院发布；9月21日15:00；面向全校学生；自由交流；场地容量有限，无需提前报名",
        "category": "activity",
        "source": "college",
        "deadline": None,
        "location": None,
        "target_audience": "全校学生",
        "status": "upcoming",
    },
]
