"""题目提供的26条校园活动模拟数据（含状态、缺失项、关联与合并信息）

约定：
- source: school(校级) / college(院级) / student(学生自发)
- status: open(报名中) / longterm(长期开放) / ended(已结束) / closed(已截止)
- 补充通知类条目（#09、#20）不单独展示，通过 MERGE_MAP 合并进原活动并生成时间线
- 时间背景：2026年9月19日考核当日
"""

ACTIVITIES_DATA = [
    {
        "id": 1,
        "title": '\u201c蓝桥杯\u201d程序设计校内训练营',
        "summary": "程序设计校内训练营，每周六定期训练，零基础可参加。",
        "category": "competition",
        "source": "school",
        "time_text": "原计划9月20日起每周六19:00（首次训练已改期，见下方变更）",
        "event_start": "2026-09-21T19:30",
        "deadline": "2026-09-24T22:00",
        "deadline_text": "9月24日22:00报名截止",
        "location": "实验楼A402（由补充通知更新）",
        "audience": "面向全校学生",
        "threshold": "零基础可参加",
        "status": "open",
        "status_note": None,
        "missing_fields": ["费用信息", "报名链接/方式"],
        "risk_flag": False,
        "risk_reason": None,
    },
    {
        "id": 2,
        "title": "AI应用入门公开课",
        "summary": "AI应用入门公开讲座，无需报名，直接前往即可。",
        "category": "lecture",
        "source": "school",
        "time_text": "9月19日19:00，预计90分钟",
        "event_start": "2026-09-19T19:00",
        "deadline": None,
        "deadline_text": "无需报名",
        "location": "计算机学院教学楼",
        "audience": "面向全校学生",
        "threshold": "无需报名",
        "status": "open",
        "status_note": "今日开始",
        "missing_fields": ["主办方的明确信息"],
        "risk_flag": False,
        "risk_reason": None,
    },
    {
        "id": 3,
        "title": "大学生创新创业项目团队招募",
        "summary": "大创项目团队招募成员，需每周稳定投入时间并提交自我介绍。",
        "category": "recruit",
        "source": "student",
        "time_text": "长期项目，报名9月22日18:00截止",
        "event_start": None,
        "deadline": "2026-09-22T18:00",
        "deadline_text": "9月22日18:00截止",
        "location": None,
        "audience": None,
        "threshold": "每周需稳定投入4小时以上；需提交简短自我介绍",
        "status": "open",
        "status_note": "开发方向名额已满（见补充说明）",
        "missing_fields": ["项目具体方向介绍", "团队联系方式"],
        "risk_flag": False,
        "risk_reason": None,
    },
    {
        "id": 4,
        "title": "数学建模竞赛经验分享会",
        "summary": "数学建模竞赛经验分享直播，不限专业。",
        "category": "lecture",
        "source": "school",
        "time_text": "直播已于9月18日19:30结束",
        "event_start": "2026-09-18T19:30",
        "deadline": None,
        "deadline_text": "直播已结束",
        "location": "线上直播",
        "audience": "不限专业",
        "threshold": None,
        "status": "ended",
        "status_note": "活动方预计9月20日上传回放",
        "missing_fields": ["回放链接"],
        "risk_flag": False,
        "risk_reason": None,
    },
    {
        "id": 5,
        "title": "校园公益志愿服务活动",
        "summary": "校园公益志愿服务，服务时长约8小时，需提前到场签到。",
        "category": "volunteer",
        "source": "school",
        "time_text": "9月27日8:30—17:00",
        "event_start": "2026-09-27T08:30",
        "deadline": "2026-09-20T12:00",
        "deadline_text": "9月20日12:00报名截止",
        "location": None,
        "audience": None,
        "threshold": "需提前到场签到；预计服务8小时",
        "status": "open",
        "status_note": None,
        "missing_fields": ["集合地点", "报名方式"],
        "risk_flag": False,
        "risk_reason": None,
    },
    {
        "id": 6,
        "title": "Web开发零基础学习小组",
        "summary": "面向零基础学生的Web开发学习小组，共6周。",
        "category": "study_group",
        "source": "student",
        "time_text": "9月23日起每周三19:30，共6周",
        "event_start": "2026-09-23T19:30",
        "deadline": None,
        "deadline_text": "报名时间未注明，满员即止",
        "location": None,
        "audience": "面向零基础学生",
        "threshold": "限30人",
        "status": "open",
        "status_note": "满员即止，建议尽快联系",
        "missing_fields": ["报名方式", "活动时间地点"],
        "risk_flag": False,
        "risk_reason": None,
    },
    {
        "id": 7,
        "title": "AI创新应用挑战赛",
        "summary": "AI创新应用竞赛，2—4人组队，先完成校内意向登记。",
        "category": "competition",
        "source": "school",
        "time_text": "校内意向登记截止9月21日18:00；作品提交截止10月20日",
        "event_start": None,
        "deadline": "2026-09-21T18:00",
        "deadline_text": "9月21日18:00前完成意向登记",
        "location": None,
        "audience": None,
        "threshold": "2—4人组队",
        "status": "open",
        "status_note": "意向登记不等同于最终作品提交",
        "missing_fields": ["比赛主题/赛制详情", "报名方式"],
        "risk_flag": False,
        "risk_reason": None,
    },
    {
        "id": 8,
        "title": "校园软件项目组招募",
        "summary": "学生项目组长期招募，开发校园实用工具。",
        "category": "recruit",
        "source": "student",
        "time_text": "长期招募，满员即止",
        "event_start": None,
        "deadline": None,
        "deadline_text": "长期招募，满员即止",
        "location": None,
        "audience": "面向大一、大二学生",
        "threshold": "希望了解Git基本操作；每周预计投入5小时",
        "status": "longterm",
        "status_note": None,
        "missing_fields": ["报名方式/联系方式"],
        "risk_flag": False,
        "risk_reason": None,
    },
    {
        "id": 9,
        "title": "程序设计训练营补充通知",
        "summary": "因场地调整，首次训练改为9月21日19:30，地点改至实验楼A402；已报名同学无需重复提交；报名截止时间不变。",
        "category": "notice",
        "source": "school",
        "status": "notice",
        "supplement_to": 1,
        "changes": [
            "首次训练时间：9月20日 → 9月21日19:30",
            "地点：改至实验楼A402",
            "报名截止时间：不变（9月24日22:00）",
            "已报名同学无需重复提交",
        ],
    },
    {
        "id": 10,
        "title": "前端开发经验交流会",
        "summary": "前端开发经验分享，线上线下同步进行，无需报名。",
        "category": "lecture",
        "source": "student",
        "time_text": "9月19日15:00—16:30",
        "event_start": "2026-09-19T15:00",
        "deadline": None,
        "deadline_text": "无需报名",
        "location": "A201（线下）+ 线上直播",
        "audience": None,
        "threshold": "无需报名",
        "status": "open",
        "status_note": "今日开始",
        "missing_fields": ["直播链接", "主办方信息"],
        "risk_flag": False,
        "risk_reason": None,
    },
    {
        "id": 11,
        "title": "大学生科研入门分享会",
        "summary": "介绍论文检索、学生科研项目和导师联系方法的入门分享会。",
        "category": "lecture",
        "source": "school",
        "time_text": "9月21日19:00—20:30",
        "event_start": "2026-09-21T19:00",
        "deadline": None,
        "deadline_text": "题目未提供报名信息",
        "location": None,
        "audience": "面向全校学生",
        "threshold": None,
        "status": "open",
        "status_note": None,
        "missing_fields": ["活动地点", "是否需要报名"],
        "risk_flag": False,
        "risk_reason": None,
    },
    {
        "id": 12,
        "title": "全国高校计算机能力挑战赛",
        "summary": "全国性计算机能力竞赛，个人参赛。",
        "category": "competition",
        "source": "school",
        "time_text": "报名截止10月5日23:59",
        "event_start": None,
        "deadline": "2026-10-05T23:59",
        "deadline_text": "10月5日23:59报名截止",
        "location": None,
        "audience": "面向本科生",
        "threshold": "个人参赛",
        "status": "open",
        "status_note": None,
        "missing_fields": ["具体费用信息", "报名方式"],
        "risk_flag": False,
        "risk_reason": None,
    },
    {
        "id": 13,
        "title": "科研助理招募",
        "summary": "协助数据整理和实验工作的科研助理岗位招募。",
        "category": "recruit",
        "source": "school",
        "time_text": "报名9月21日截止",
        "event_start": None,
        "deadline": "2026-09-21T23:59",
        "deadline_text": "9月21日截止报名",
        "location": None,
        "audience": "仅限大二及以上学生",
        "threshold": "每周预计投入6小时",
        "status": "open",
        "status_note": None,
        "missing_fields": ["投递方式", "是否有报酬"],
        "risk_flag": False,
        "risk_reason": None,
    },
    {
        "id": 14,
        "title": "Git与GitHub零基础工作坊",
        "summary": "面向大一新生的Git与GitHub零基础实操工作坊。",
        "category": "workshop",
        "source": "school",
        "time_text": "9月21日19:00—20:30",
        "event_start": "2026-09-21T19:00",
        "deadline": None,
        "deadline_text": "需提前预约，以审核通知为准",
        "location": None,
        "audience": "主要面向大一新生",
        "threshold": "限40人；提交报名表不代表最终录取",
        "status": "open",
        "status_note": "预约后需等待审核，报名≠录取",
        "missing_fields": ["活动地点", "预约方式"],
        "risk_flag": False,
        "risk_reason": None,
    },
    {
        "id": 15,
        "title": "AI应用创意挑战",
        "summary": "AI应用创意比赛，先提交创意方案，进入展示环节后可再组队。",
        "category": "competition",
        "source": "school",
        "time_text": "创意方案9月23日23:59前提交；最终作品9月30日前提交",
        "event_start": None,
        "deadline": "2026-09-23T23:59",
        "deadline_text": "9月23日23:59方案截止",
        "location": None,
        "audience": None,
        "threshold": "允许个人或团队参加；进入展示环节后可再组队",
        "status": "open",
        "status_note": "两段式截止：方案9/23、作品9/30",
        "missing_fields": ["提交方式", "奖项设置"],
        "risk_flag": False,
        "risk_reason": None,
    },
    {
        "id": 16,
        "title": "校园摄影志愿者招募",
        "summary": "参与校内大型活动摄影的志愿者长期招募。",
        "category": "volunteer",
        "source": "school",
        "time_text": "长期招募",
        "event_start": None,
        "deadline": None,
        "deadline_text": "具体报名截止时间未注明",
        "location": None,
        "audience": None,
        "threshold": "有摄影设备者优先，但不作硬性要求",
        "status": "longterm",
        "status_note": None,
        "missing_fields": ["报名方式", "截止时间"],
        "risk_flag": False,
        "risk_reason": None,
    },
    {
        "id": 17,
        "title": "Python程序设计学习资料合集",
        "summary": "包含课程、练习和项目案例的Python学习资料，长期开放。",
        "category": "resource",
        "source": "school",
        "time_text": "资料长期开放；当前网盘提取信息有效至9月22日",
        "event_start": None,
        "deadline": "2026-09-22T23:59",
        "deadline_text": "网盘链接9月22日失效，后续统一更新",
        "location": "线上（网盘）",
        "audience": None,
        "threshold": None,
        "status": "longterm",
        "status_note": "注意：当前网盘链接9/22前失效，尽快保存",
        "missing_fields": ["更新后的链接"],
        "risk_flag": False,
        "risk_reason": None,
    },
    {
        "id": 18,
        "title": "网络安全兴趣交流小组",
        "summary": "面向CTF、Web安全等方向-interesting学生的兴趣交流小组。",
        "category": "study_group",
        "source": "student",
        "time_text": "首次交流9月19日19:30；之后每两周一次",
        "event_start": "2026-09-19T19:30",
        "deadline": None,
        "deadline_text": "题目未提供报名信息",
        "location": None,
        "audience": "对CTF、Web安全等方向感兴趣的学生",
        "threshold": "不限基础",
        "status": "open",
        "status_note": "今日首次活动",
        "missing_fields": ["活动地点/参与方式"],
        "risk_flag": False,
        "risk_reason": None,
    },
    {
        "id": 19,
        "title": "学生创新项目路演观摩",
        "summary": "学生创新项目路演观摩活动，报名已截止，现场如有余位可候补入场。",
        "category": "lecture",
        "source": "school",
        "time_text": "9月20日14:30",
        "event_start": "2026-09-20T14:30",
        "deadline": "2026-09-18T22:00",
        "deadline_text": "报名已于9月18日22:00截止",
        "location": None,
        "audience": None,
        "threshold": None,
        "status": "closed",
        "status_note": "报名已截止；活动方说明现场如仍有余位，可接受候补入场",
        "missing_fields": ["候补入场具体规则"],
        "risk_flag": False,
        "risk_reason": None,
    },
    {
        "id": 20,
        "title": "创新创业项目团队补充说明",
        "summary": "开发方向名额已满，现主要补充设计与材料成员；9月22日18:00截止；此前已投递者无需重复提交。",
        "category": "notice",
        "source": "student",
        "status": "notice",
        "supplement_to": 3,
        "changes": [
            "开发方向：名额已满，不再接收",
            "现主要补充：设计与材料方向成员",
            "截止时间不变：9月22日18:00",
            "此前已投递者无需重复提交",
        ],
    },
    {
        "id": 21,
        "title": "计算机学院AI产品设计分享会",
        "summary": "计算机学院发布的AI产品设计主题分享会。",
        "category": "lecture",
        "source": "college",
        "source_name": "计算机学院",
        "time_text": "9月20日19:00",
        "event_start": "2026-09-20T19:00",
        "deadline": None,
        "deadline_text": "无需报名，座位有限",
        "location": "明德楼B203",
        "audience": "面向全校学生",
        "threshold": "无需报名；座位有限建议早到",
        "status": "open",
        "status_note": "座位有限，建议提前到场",
        "missing_fields": ["分享嘉宾信息"],
        "risk_flag": False,
        "risk_reason": None,
    },
    {
        "id": 22,
        "title": "学生发起｜周末羽毛球约球",
        "summary": "学生自发组织的周末羽毛球活动，费用AA。",
        "category": "sport",
        "source": "student",
        "time_text": "9月20日16:00",
        "event_start": "2026-09-20T16:00",
        "deadline": None,
        "deadline_text": "题目未提供报名信息",
        "location": "场地待最终确认",
        "audience": "计划6—8人",
        "threshold": "费用AA",
        "status": "open",
        "status_note": "场地尚未最终确认",
        "missing_fields": ["具体场地", "报名方式/联系人"],
        "risk_flag": False,
        "risk_reason": None,
    },
    {
        "id": 23,
        "title": "学生发起｜AI工具交流搭子招募",
        "summary": "学生自发的AI工具学习交流，报名后拉群。",
        "category": "team",
        "source": "student",
        "time_text": "拟于9月21日晚开展（具体时间未定）",
        "event_start": None,
        "deadline": None,
        "deadline_text": "题目未提供报名信息",
        "location": "具体地点未确定",
        "audience": "欢迎零基础",
        "threshold": "报名后拉群",
        "status": "open",
        "status_note": "时间地点均未最终确定",
        "missing_fields": ["具体时间", "具体地点"],
        "risk_flag": False,
        "risk_reason": None,
    },
    {
        "id": 24,
        "title": '学生发起｜\u201c校园兼职福利分享\u201d',
        "summary": '称\u201c零门槛、日结\u201d，要求添加私人微信获取详情。',
        "category": "other",
        "source": "student",
        "time_text": "未注明",
        "event_start": None,
        "deadline": None,
        "deadline_text": "未注明",
        "location": None,
        "audience": None,
        "threshold": None,
        "status": "open",
        "status_note": None,
        "missing_fields": ["主办方", "活动时间", "地点", "兼职具体内容"],
        "risk_flag": True,
        "risk_reason": "无主办方、无地点、无完整内容，且引导添加私人微信；\u201c零门槛、日结\u201d为典型推广话术，请谨慎判断",
    },
    {
        "id": 25,
        "title": "学生发起｜数码新品体验交流",
        "summary": "标题为技术交流，正文主要介绍某商家优惠及购买链接。",
        "category": "other",
        "source": "student",
        "time_text": "未注明",
        "event_start": None,
        "deadline": None,
        "deadline_text": "未注明",
        "location": None,
        "audience": None,
        "threshold": None,
        "status": "open",
        "status_note": None,
        "missing_fields": ["活动时间", "地点", "主办方"],
        "risk_flag": True,
        "risk_reason": "标题与正文内容不符：名为技术交流，实为商家推广及购买链接，疑似广告",
    },
    {
        "id": 26,
        "title": "外国语学院校园语言角",
        "summary": "外国语学院发布的校园语言角自由活动。",
        "category": "activity",
        "source": "college",
        "source_name": "外国语学院",
        "time_text": "9月21日15:00",
        "event_start": "2026-09-21T15:00",
        "deadline": None,
        "deadline_text": "无需提前报名",
        "location": None,
        "audience": "面向全校学生",
        "threshold": "场地容量有限；无需提前报名",
        "status": "open",
        "status_note": "场地容量有限，建议早点到场",
        "missing_fields": ["具体场地"],
        "risk_flag": False,
        "risk_reason": None,
    },
]

# 类别中文名映射
CATEGORY_LABELS = {
    "competition": "竞赛",
    "lecture": "讲座分享",
    "recruit": "招募",
    "study_group": "学习小组",
    "volunteer": "志愿服务",
    "workshop": "工作坊",
    "resource": "学习资料",
    "sport": "运动约球",
    "team": "组队交流",
    "activity": "校园活动",
    "notice": "补充通知",
    "other": "其他",
}

# 补充通知合并映射：notice_id -> (target_id, 通知数据)
def get_merged_activities() -> list:
    """返回合并补充通知后的活动列表。

    #09 合并进 #01、#20 合并进 #03，被合并条目不出现在主列表中，
    主条目附带 timeline（变更时间线）与 supplements 字段。
    """
    notices = {}
    main_items = []
    for item in ACTIVITIES_DATA:
        if item.get("status") == "notice":
            target = item["supplement_to"]
            notices.setdefault(target, []).append(item)
        else:
            main_items.append(dict(item))

    for item in main_items:
        related_notices = notices.get(item["id"], [])
        timeline = []
        # 原始信息作为时间线第一条
        timeline.append({
            "time": "原始通知",
            "text": item["summary"],
            "is_update": False,
        })
        supplements = []
        for n in related_notices:
            timeline.append({
                "time": f'补充通知（#{n["id"]:02d}）',
                "text": n["summary"],
                "is_update": True,
                "changes": n["changes"],
            })
            supplements.append({
                "id": n["id"],
                "title": n["title"],
                "changes": n["changes"],
            })
        item["timeline"] = timeline
        item["supplements"] = supplements
        item["related"] = [{"id": n["id"], "note": "已有补充通知，信息已合并显示"} for n in related_notices]
    return main_items


def get_activity_by_id(activity_id: int):
    for item in get_merged_activities():
        if item["id"] == activity_id:
            return item
    # 用户发布的内容
    for item in load_user_posts():
        if item["id"] == activity_id:
            return item
    return None


# ---------- 用户发布内容的文件持久化 ----------
import json
import os

_USER_POSTS_FILE = os.path.join(os.path.dirname(__file__), "user_posts.json")


def load_user_posts() -> list:
    if not os.path.exists(_USER_POSTS_FILE):
        return []
    try:
        with open(_USER_POSTS_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return []


def save_user_post(post: dict) -> dict:
    posts = load_user_posts()
    next_id = max([p["id"] for p in posts], default=100) + 1
    post["id"] = next_id
    post.setdefault("status", "open")
    post.setdefault("source", "student")
    post.setdefault("timeline", [{"time": "发布于考核当日", "text": post["summary"], "is_update": False}])
    post.setdefault("supplements", [])
    post.setdefault("related", [])
    posts.append(post)
    with open(_USER_POSTS_FILE, "w", encoding="utf-8") as f:
        json.dump(posts, f, ensure_ascii=False, indent=2)
    return post
